# Generated by Django 3.2.25 on 2024-08-05 04:52

from django.db import migrations, models
import django.utils.timezone
import enumfields.fields
import membership.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', enumfields.fields.EnumField(enum=membership.enums.MembershipEnum, max_length=10)),
                ('benefits', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
