# Generated by Django 3.2.25 on 2024-08-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
