# Generated by Django 3.2.25 on 2024-08-05 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membership_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='next_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_memberships', to='membership.membership'),
        ),
    ]
