# Generated by Django 3.2.25 on 2024-08-05 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import promotion.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(default='DIRECT_DISCOUNT', enum=promotion.enums.PromotionTypeEnum, max_length=32)),
                ('value', models.FloatField()),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='promotion.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionConditionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', enumfields.fields.EnumField(default='AND', enum=promotion.enums.PromotionGroupOperatorEnum, max_length=32)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups', to='promotion.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', enumfields.fields.EnumField(default='product', enum=promotion.enums.PromotionConditionFieldEnum, max_length=10)),
                ('data_type', enumfields.fields.EnumField(default='STRING', enum=promotion.enums.PromotionConditionFieldDataTypeEnum, max_length=10)),
                ('operator', enumfields.fields.EnumField(default='EQUAL', enum=promotion.enums.PromotionOperatorEnum, max_length=32)),
                ('value', models.CharField(max_length=512)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='promotion.promotionconditiongroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
