# Generated by Django 3.2.25 on 2024-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
