# Generated by Django 3.2.25 on 2024-08-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
