# Generated by Django 3.2.25 on 2024-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderpromotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='final_total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
